### ISSUE TITLE
Weekplan

### ISSUE THREAD

**Issue by bennyboer** [Fachschaft07/Guide7#30]
Implement the ZPA weekplan. We will first need a widget to display the events. Maybe write an own one.

**Comment by LokiNightray** [comment]
There seems to be a courseplan for the fk10 on https://nine.wi.hm.edu/.
But only with login-data provided.
https://shortcut.wi.hm.edu/apps/fillter/login?returnUrl=%2Fcalendar
Most other sites of this mobile app use a rest-api and load all the data via javascript, so there may be a way to get the courseplan for the WI and Master WI students via a further login + some rest calls.
The mobile webapp is available on:
https://shortcut.wi.hm.edu/apps/fillter/home 
if you may want to analyse more of the rest-calls

**Comment by bennyboer** [comment]
## Acceptance Criteria Draft

- [ ] On first start of the week view we need a setup (FK 07 (Use ZPA) or FK 10 (use Nine))
- [ ] Show events of two days when in `portrait` mode (Configurable)
- [ ] Show events of three days when in `landscape` mode (Configurable)
- [ ] Show events per day in a list form (See old Guide7 version, can be similar)
- [ ] Multiple events at the same time can be shown which have to be displayed **side by side**
- [ ] Background task which will check every 30 minutes if an event within the next **7** days changed, update the next **7** days
- [ ] Show notification in case an event changed or new ones appeared within the next **7** days
- [ ] Use floating action button to add new custom events which will be stored persistently independent from the events from ZPA or Nine
- [ ] Custom events need to be editable in the detail view (maybe by floating action button)
- [ ] Enter detail view showing additional information about the tapped event (fullscreen)
- [ ] Events should be loaded day by day (using the ZPA or Nine API). When scrolling horizontally (switch showed days) a loading indicator is displayed when the days events have not been loaded yet. Otherwise shows the days events.
- [ ] Cache events from ZPA or Nine (the background task needs something to compare

**Comment by bennyboer** [comment]
@LokiNightray Yes, you're right, I don't like dropdowns, instead you could just set up all your services in the beginning or later in the settings. I'm updating the acceptance criteria.

**Comment by LokiNightray** [comment]
@bennyboer Sounds good, was just thinking about further stuff where such a dropdown may makes some more sence i.e. for the free rooms search and that it may be convenient too stick with a common User Interface for such services.
But if there is a way too do it without dropdowns then all the better.

**Comment by bennyboer** [comment]
@LokiNightray Yeah, for the roomsearch we'll need it. Maybe we can provide a hidden filter dropdown via the floating action button menu to filter by faculty in case you set up multiple services for events. Lets keep that in mind, but I'd rather keep that as an additional issue.

**Comment by bennyboer** [comment]
[This](https://github.com/renefloor/side_header_list_view) could be an alternative to the classic day view which will scroll horizontally (see old Guide7 java client).

@LokiNightray @thomai @Gleydar @Chrysotomus What do you think? Do you have additional ideas?

**Comment by bennyboer** [comment]
Do not implement nine integration for now, just the ZPA services.

**Comment by thomai** [comment]
> @LokiNightray @thomai @Gleydar @Chrysotomus What do you think? Do you have additional ideas?

Looks like a very nice ui! :+1: 
I am not able to see the alternative because I am not able to use the Guide7 app (I am not a student at the HM anymore).

**Comment by Chrysotomus** [comment]
I think the alternative day view where you scroll vertically is great ^^
Scrolling up and down on a smartphone seems  way more intuitive to me than scrolling horizontally. Sadly I can't test (and compare it to) the old Guide7 app as my smartphone is currently broken.

**Comment by bennyboer** [comment]
@thomai @Chrysotomus In that case we'll use that one I guess! You are right that it matches the way most people would want to use their phone rather by scrolling vertically than horizontally. Besides that you'll be able to put more information than in a little rectangular event box.

**Comment by bennyboer** [comment]
Tasks left to do:

- Cache events
- Custom events / Edit events
- Background task refreshing tasks and notifying about changes
- Event detail view
- Events should look a little nicer

**Comment by bennyboer** [comment]
Detail view ain't pretty but works.
