### ISSUE TITLE
Mealplan (Speiseplan)

### ISSUE THREAD

**Issue by bennyboer** [Fachschaft07/Guide7#31]
Implement the mealplan. (See the old implementation in the java android Guide7 version).

**Comment by thomai** [comment]
https://openmensa.org/api/v2/canteens//141/meals <- speiseplan mensa lothstraße

**Comment by thomai** [comment]
https://openmensa.org/api/v2/canteens//142/meals <- speiseplan mensa pasing

**Comment by LokiNightray** [comment]
urls taken from: https://shortcut.wi.hm.edu/apps/fillter/mensa

**Comment by hmkrivoj** [comment]
Are there any ideas on how to navigate to the meal plan?
Seperate page on the bottomnavigationbar? New action on the FloatingActionButton?

**Comment by hmkrivoj** [comment]
OpenMensa doesn't support the Studentenwerk's labels for vegan, veggy, pork, beef etc.

**Comment by hmkrivoj** [comment]
Old parser of mine which gets the canteens but lacks alergenes and the veggy/vegan labels:
[https://github.com/hmkrivoj/Mensapp/blob/master/app/src/main/java/edu/hm/cs/krivoj/mensapp/api/Downloader.java](https://github.com/hmkrivoj/Mensapp/blob/master/app/src/main/java/edu/hm/cs/krivoj/mensapp/api/Downloader.java)
Old parser of Ben which lacks the canteens stuff but gets alergenes and labels:
[https://github.com/Fachschaft07/Guide7/blob/develop/java-app/app/src/main/java/de/be/thaw/connect/parser/canteen/MenuParser.java](https://github.com/Fachschaft07/Guide7/blob/develop/java-app/app/src/main/java/de/be/thaw/connect/parser/canteen/MenuParser.java)

**Comment by thomai** [comment]
If you want to save traffic, battery life and so on: Maybe it would be a good idea to use a REST service and a centralized parser to preprocess data like that. Just an idea :)
