### ISSUE TITLE
Services visible when logged out

### ISSUE THREAD

**Issue by bennyboer** [Fachschaft07/Guide7#39]
Some services (public notice board, appointments, etc.) can be easily be made visible for non-logged-in users. People without ZPA login might want to use the public app services as well.

Tasks to do for completion:

- [x] Make login skippable (Smaller non-raised button below the login button)
  - [x] Implement static method `isLoggedIn()` in another utility class `ZPA` which is checking the `CredentialStorage` for stored credentials. We can then call `ZPA.isLoggedIn()` from anywhere in the app.
- [x] Hide non-viewable items in the navigation(s) when not logged in
- [x] Implement public notice board for non-logged in users

**Comment by bennyboer** [comment]
Login now skippable.
Public notice board will load instead of the personal when not logged in.
Login/Logout button in the navigation view based on the login state.

**Comment by bennyboer** [comment]
@thomai This one will be interesting for you, as you no longer need to login but just skip the login. In that case the public notice board will be shown instead of the personal.

**Comment by thomai** [comment]
Thank you very much! :smiley:
