### ISSUE TITLE
Privacy policy statement

### ISSUE THREAD

**Issue by bennyboer** [Fachschaft07/Guide7#47]
I already added a view in the navigation view of the app for the privacy policy statement which we'll definitely need.

@LokiNightray @thomai You mentioned that the university has a pattern which we must use (in case the app is distributed by us and not over me), Can we get that?

**Comment by LokiNightray** [comment]
@bennyboer i don't know if there is a special pattern needed for that. 
The old app is published under Apache License, Version 2.0
Regarding Privacy Policy: There is one from the University itself:
https://www.hm.edu/sekundaer_navigation/impressum/datenschutz/index.de.html
We may could just adapt this one to our needs.
@thomai do you know anything regarding license agreements and privacy policies that are needed in this case

**Comment by thomai** [comment]
> @bennyboer i don't know if there is a special pattern needed for that.
> The old app is published under Apache License, Version 2.0
> Regarding Privacy Policy: There is one from the University itself:
> https://www.hm.edu/sekundaer_navigation/impressum/datenschutz/index.de.html
> We may could just adapt this one to our needs.
The privacy policy of the university is out of scope within this context. @bennyboer is the person who publishes the app in official matters. Therefore the university does not care about the privacy policy. Actually the FS07 has no rights to decide the contents of the privacy policy.

> @thomai do you know anything regarding license agreements and privacy policies that are needed in this case
In the past, the Apache License (Version 2) has been used. I'd recommend to use it further on. We may discuss other licenses if you want to use another one :+1: 
What about advantages/disadvantages?

**Comment by bennyboer** [comment]
@thomai Well ok, then I'm going to just write a privacy policy statement ;)

Currently the project is under the MIT License (See [here](https://github.com/Fachschaft07/Guide7/blob/develop/LICENSE)) which I like because of its simplicity. There are pretty much no downsides compared to apache 2 and it is (just my feeling) more widely known and used.

**Comment by bennyboer** [comment]
Write one in Markdown format so that it can easily be shown as GitHub Page (needed for Google Play, as they want a URL providing the privacy policy) and in app.

**Comment by bennyboer** [comment]
Done!

**Comment by bennyboer** [comment]
https://github.com/Fachschaft07/Guide7/blob/develop/res/docs/privacy_policy/privacy_policy_de.md
